# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run at every 5-minute interval
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Set a timeout for this job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}  # Use the personal access token here
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run hashhead
      run: python hashhead.py  # Replace with your Python script filename
      
    - name: Commit and push if it changed
      run: |
        git config user.name "TreeCityWes"
        git config user.email "wes@treecitytrading.us"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data updated on ${timestamp}" || exit 0
        git push https://${{ secrets.GH_TOKEN }}@github.com/TreeCityWes/HashHead.git HEAD:main
