name: Run Scraper and Update Data

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Set a timeout for this job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run hashhead
      run: python hashhead.py  # Replace with your Python script filename
      
    - name: Commit and push if it changed
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data updated on ${timestamp}" || exit 0
        git push https://${{ secrets.GH_TOKEN }}github.com/TreeCityWes/hashhead.git/ HEAD:main
