name: Python application
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Enables manual triggering.
permissions:
  contents: read
jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
      
    - name: Run hashhead
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        python hashhead.py
      
    - name: Commit and push if it changed
      run: |
        git config user.name "TreeCityWes"
        git config user.email "wes@treecitytrading.us"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        timestamp=$(date -u)
        git commit -m "Data updated on ${timestamp}" || exit 0
        git pull --rebase origin main
        git push https://${{ secrets.GH_TOKEN }}@github.com/TreeCityWes/HashHead.git HEAD:main
